Placeholdes display
divio/djangocms-rest-api pull request #11
Opened 2016-12-23 08:03 UTC by moridyn

2016-12-23 11:53 UTC, czpython requested changes

2016-12-23 11:53 UTC, czpython commented on djangocms_rest_api/serializers/base.py
> +        if not serializer_class and instance:
why pass instance? `plugin.plugin_type` and `instance.plugin_type` should always match

2016-12-23 12:29 UTC, moridyn commented on djangocms_rest_api/serializers/base.py
> +        if not serializer_class and instance:
plugin does not have attribute plugin_type or at least some like LinkPlugin. Got AttributeError in there

2016-12-23 12:31 UTC, czpython commented on djangocms_rest_api/serializers/base.py
> +        if not serializer_class and instance:
It has to have it.. LinkPlugin inherits from `CMSPlugin` which has it.
If it throws an `AttributeError` then its not good behavior, please have a look.

2016-12-23 15:23 UTC, czpython commented on djangocms_rest_api/serializers/base.py
> +                obj, model=getattr(plugin, 'model', None), plugin=plugin, context=self.context)
plugin will always have a `model` attribute.
So you can do `plugin.model`

2016-12-26 13:55 UTC, czpython approved these changes

2016-12-27 11:55 UTC, merged