React base
divio/djangocms-rest-api pull request #6
Opened 2016-11-16 20:18 UTC by moridyn

Simple react app which only renders menu

2016-11-17 07:29 UTC, FinalAngel requested changes

2016-11-17 07:29 UTC, FinalAngel commented on example_project/react-app/README.md
> +To start project you need node version 6 or more
we normally use restructured text for all readme's

2016-11-17 07:29 UTC, FinalAngel commented on example_project/react-app/public/index.html
> +  <head>
always 4 spaces

2016-11-17 07:29 UTC, FinalAngel commented on example_project/react-app/src/App.css
> +.App {
lowercase

2016-11-17 07:29 UTC, FinalAngel commented on example_project/react-app/src/App.css
> +    animation: App-logo-spin infinite 20s linear;
also lowercase for variables or names

2016-11-17 07:29 UTC, FinalAngel commented on example_project/requirements.txt
>  django-treebeard>=4.0
you need to add ``django-cors-headers`` as well to the requirements

2016-11-17 07:29 UTC, FinalAngel commented on example_project/README.md
> + - call migrations: ./manage.py migrate
first you need to create a superuser ``python manage.py createsuperuser``

2016-11-17 07:29 UTC, FinalAngel commented on example_project/README.md
> + - run dev server: ./manage.py runserver
also mention that you can access the api via ``http://localhost:8000/en/api/``

2016-11-17 07:29 UTC, FinalAngel commented on example_project/README.md
> + - run dev server: ./manage.py runserver
this starts the django runserver where I can add pages etc. how can I access the react app?

2016-11-17 07:40 UTC, FinalAngel commented on example_project/README.md
> + - run dev server: ./manage.py runserver
Integrate the README from the react_app directly here, noting:

```
- open a new terminal window
- navigate to the react-app
- run npm install
- run npm start

```

and then the additional infos regarding localserver etc from the react-app's readme

2016-11-17 07:40 UTC, FinalAngel commented on example_project/react-app/README.md
> + - npm start
this throws an error for me:

```
⋊> ~/S/d/e/react-app on react_base  npm start                           08:38:59

> react-app@0.1.0 start /Users/finalangel/Sites/djangocms-rest-api/example_project/react-app
> react-scripts start

/Users/finalangel/Sites/djangocms-rest-api/example_project/react-app/node_modules/react-scripts/scripts/start.js:46
var isSmokeTest = process.argv.some(arg => arg.indexOf('--smoke-test') > -1);
                                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-app@0.1.0 start script 'react-scripts start'.
npm ERR! This is most likely a problem with the react-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/finalangel/Sites/djangocms-rest-api/example_project/react-app/npm-debug.log
```

2016-11-17 08:19 UTC, vxsx commented on example_project/react-app/README.md
> + - npm start
you have old node :)
try with node 6

2016-11-18 08:51 UTC, FinalAngel commented on example_project/react-app/README.md
> + - npm start
Yes, eventually note the requirements of the node / npm version

2016-11-21 08:22 UTC, FinalAngel commented on example_project/requirements.txt
>  django-treebeard>=4.0
@moridyn  missed one here

2016-11-24 07:39 UTC, FinalAngel requested changes
@vxsx wdyt?

2016-11-24 07:39 UTC, FinalAngel commented on example_project/README.md
> +Test application for Django Cms Rest Api
django CMS Rest API

2016-11-24 07:39 UTC, FinalAngel commented on example_project/README.md
> +==============================
please use .rst as default format

2016-11-24 07:39 UTC, FinalAngel commented on example_project/README.md
> +* activate env with: source venv/bin/activate
mark them as code via ` ` > ``virtualenv venv``

2016-11-24 07:39 UTC, FinalAngel commented on example_project/README.md
> +
additional space

2016-11-24 08:07 UTC, vxsx reviewed
looks good overall

2016-12-14 15:54 UTC, merged